### ISSUE TITLE
[Xamarin.Forms] expected class 'System.nfloat' in assembly 'Xamarin.iOS'

### ISSUE THREAD

**Issue by TimLariviere** [fabulousfx/net6.0-mobile-fsharp#6]
XF iOS project does compile and run, but crashes with this error:
```
Could not register the assembly 'Xamarin.Forms.Platform.iOS': System.TypeLoadException: Could not resolve type with token 0100005d from typeref (expected class 'System.nfloat' in assembly 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065')
   at System.Reflection.MonoMethodInfo.GetMethodInfo(IntPtr handle)
   at System.Reflection.RuntimeMethodInfo.GetPseudoCustomAttributes()
   at System.Reflection.CustomAttribute.GetPseudoCustomAttributes(ICustomAttributeProvider obj, Type attributeType)
   at System.Reflection.CustomAttribute.GetCustomAttributesBase(ICustomAttributeProvider obj, Type attributeType, Boolean inheritedOnly)
   at System.Reflection.CustomAttribute.GetCustomAttributes(ICustomAttributeProvider obj, Type attributeType, Boolean inherit)
   at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Type attributeType, Boolean inherit)
   at Registrar.SharedDynamic.GetOneAttribute[ExportAttribute](ICustomAttributeProvider provider)
   at Registrar.DynamicRegistrar.GetExportAttribute(MethodBase method)
   at Registrar.Registrar.RegisterTypeUnsafe(Type type, List`1& exceptions)
   at Registrar.Registrar.RegisterAssembly(Assembly assembly)
```

Might be related to https://github.com/xamarin/xamarin-macios/issues/13087

**Comment by TimLariviere** [comment]
Fixing it would mean recompiling `Xamarin.Forms.Platform.iOS` against `net6.0-ios`
Meaning we would need to make our own fork of Xamarin.Forms

**Comment by edgarfgp** [comment]
I saw a related discussion on twitter . https://twitter.com/praeclarum/status/1480583047833550848?s=21

**Comment by edgarfgp** [comment]
Looks like there is version of Xamarin.Forms that works on Net 6 https://twitter.com/praeclarum/status/1480939068930158595?s=21

**Comment by TimLariviere** [comment]
~~I tried this port, but still have the same issue~~

It does work after cleaning obj/bin!
