### ISSUE TITLE
[Maui - Android] Crash at start up

### ISSUE THREAD

**Issue by TimLariviere** [fabulousfx/net6.0-mobile-fsharp#9]
```
01-26 23:01:38.056  7345  7345 D AndroidRuntime: Shutting down VM
01-26 23:01:38.056  7345  7345 E AndroidRuntime: FATAL EXCEPTION: main
01-26 23:01:38.056  7345  7345 E AndroidRuntime: Process: org.fabulous.MauiApp, PID: 7345
01-26 23:01:38.056  7345  7345 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.InvalidCastException: Unable to convert instance of type 'Android.Widget.FrameLayout' to type 'AndroidX.CoordinatorLayout.Widget.CoordinatorLayout'.
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Java.Interop.JavaObjectExtensions.CastClass(IJavaObject instance, Type resultType)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Java.Interop.JavaObjectExtensions._JavaCast[CoordinatorLayout](IJavaObject instance)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Java.Interop.JavaObjectExtensions.JavaCast[CoordinatorLayout](IJavaObject instance)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Android.Runtime.Extensions.JavaCast[CoordinatorLayout](IJavaObject instance)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.Platform.NavigationRootManager.get_NavigationLayout()
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.Platform.NavigationRootManager.get_RootView()
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.Handlers.WindowHandler.MapContent(WindowHandler handler, IWindow window)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.Controls.Window.MapContent(WindowHandler handler, IWindow view)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.WindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.Platform.HandlerExtensions.SetHandler(Context nativeElement, IElement element, IMauiContext context)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.Platform.HandlerExtensions.SetWindowHandler(Activity activity, IWindow window, IMauiContext context)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.Platform.ApplicationExtensions.CreateNativeWindow(Activity activity, IApplication application, Bundle savedInstanceState)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at MauiApp.MainActivity.OnCreate(Bundle savedInstanceState)
01-26 23:01:38.056  7345  7345 E AndroidRuntime:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at crc647cfc421ca65c7b98.MainActivity.n_onCreate(Native Method)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at crc647cfc421ca65c7b98.MainActivity.onCreate(MainActivity.java:38)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8051)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8031)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-26 23:01:38.056  7345  7345 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by TimLariviere** [comment]
Solved by using https://github.com/fabulousfx/FSharp.Android.Resource and calling `Resources.UpdateIdValues()` in `OnCreate`
